### ISSUE TITLE
Successful Upgrade All returns exit code 1

### ISSUE THREAD

**Issue by azweb76** [godaddy/node-cluster-service#61]
`cservice "upgrade all /usr/local/dps-server/b8d4b06bfb52d483dbd80302b4c519dcfdb7bbe5/worker" --accessKey XXXX
'"5 workers upgraded successfully"'
echo $? # returns 1`

**Comment by asilvas** [comment]
This appears to be working as intended. What am I missing?

**Comment by asilvas** [comment]
@azweb76 please review

**Comment by asilvas** [comment]
fixed
