### ISSUE TITLE
4 Failed Test when run against Node 0.12

### ISSUE THREAD

**Issue by azweb76** [godaddy/node-cluster-service#62]
Service fails when running under Node 0.12. Run `npm test` using 0.12 for an example.

**Comment by asilvas** [comment]
Thanks @azweb76 -- I'll look into it.

**Comment by asilvas** [comment]
The failures appear to be mostly benign, race conditions likely only to be found if scripting specific failure scenarios (which the tests are doing). Still important to fix, but lowering priority.

**Comment by azweb76** [comment]
Additional info... our app (DPS Web) will not run when upgrading Node to 0.12.

**Comment by DullReferenceException** [comment]
I believe that https://github.com/godaddy/node-cluster-service/pull/66 fixed this.
