### ISSUE TITLE
[DEP0007] DeprecationWarning: worker.suicide is deprecated. Please use worker.exitedAfterDisconnect.

### ISSUE THREAD

**Issue by jakepusateri** [godaddy/node-cluster-service#75]
A couple of references are present. I can PR the fix if you'd like.

https://github.com/godaddy/node-cluster-service/search?utf8=%E2%9C%93&q=suicide&type=

**Comment by asilvas** [comment]
PR would be welcome!

**Comment by raphamorim** [comment]
I can work on it, if it's okay :D
