### ISSUE TITLE
Memory leak in the message bus

### ISSUE THREAD

**Issue by jakepusateri** [godaddy/node-cluster-service#78]
It doesn't look like the `waiters` object is ever cleared of a waiter. 

https://github.com/godaddy/node-cluster-service/blob/master/lib/message-bus.js#L14

This means every time you send a message, in my case `cluster.trigger('info')`, it will grow the waiters object without bound.

https://github.com/godaddy/node-cluster-service/blob/master/lib/message-bus.js#L68

This is clear in the memory profile:

![image](https://user-images.githubusercontent.com/2494130/40590334-cade41b8-61b1-11e8-8206-d6e4afa0355b.png)

18673 waiters have been added, approximately consistent with this function being called once every 5 seconds for 24 hours.

Is the waiter only used in a one-time callback? If so, can it be deleted from `waiters` after `processMessage` looks it up?

https://github.com/godaddy/node-cluster-service/blob/master/lib/message-bus.js#L95

**Comment by asilvas** [comment]
Good catch. A timeout would be nice as well. PR welcome!

**Comment by hunter9291** [comment]
The delete in processMessage works great, but the one in the cleanupCheck seems to be using the wrong key to lookup the waiter in the waiter array. It is using "waiterId" (the globally scoped increment var that may actually be different after 5 seconds) when it should be using "msg.waiterId" (with the "id" prefix + the correct id that was used to add the waiter to waiters object). 

If that seems sane, I can push a branch up to address that. Let me know @asilvas !

**Comment by asilvas** [comment]
@hunter9291 great catch, PR welcome!
